"""empty message

Revision ID: 569300a2fb67
Revises: 
Create Date: 2021-08-01 09:01:29.323794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569300a2fb67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deck')
    # ### end Alembic commands ###
