"""empty message

Revision ID: abe254951a81
Revises: da9975865e69
Create Date: 2021-08-02 19:58:49.106498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abe254951a81'
down_revision = 'da9975865e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('order', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'order')
    # ### end Alembic commands ###
