"""empty message

Revision ID: e75d8a17f3d0
Revises: 3c5d1da4c016
Create Date: 2021-08-01 10:15:23.220930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e75d8a17f3d0'
down_revision = '3c5d1da4c016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('cue', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deck_id', 'category_id', 'cue')
    )
    op.drop_constraint('category_name_key', 'category', type_='unique')
    op.create_unique_constraint(None, 'category', ['deck_id', 'name'])
    op.drop_constraint('pack_name_key', 'pack', type_='unique')
    op.create_unique_constraint(None, 'pack', ['deck_id', 'name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pack', type_='unique')
    op.create_unique_constraint('pack_name_key', 'pack', ['name'])
    op.drop_constraint(None, 'category', type_='unique')
    op.create_unique_constraint('category_name_key', 'category', ['name'])
    op.drop_table('card')
    # ### end Alembic commands ###
